%x2y2z2
%phi_x=(1 sqrt(3)*(1-2t));phi_y=(1 sqrt(2)*sin(2pit));phi_z=(1 sqrt(2)*cos(4pit));
%lambda0=lambda0=@(t) (0.3*cos(2*pi*t)+1);  
clear all
load xi_ybs200.mat %xi_y generated by R package MTS, which is a VAR(1) time series. Xi=P*Xi(t-1)+epsilon(t), where P=diag(0.5, 0, 0.5, 0)
n=200;   %# of subjects
m=n;   %# of days
rep=50;
for i=1:rep
    i
    %     % %%Bivariate setting(4 dimesion) for X, Y.
    mu_x=zeros(1,4);
    sigma_x1=[0.5 0; 0 0.2];sigma_x2=[0.2 0.15;0.15 0.1]; %setting in xy02z02
    sigma_x=[sigma_x1 sigma_x2;sigma_x2' sigma_x1];
%     mu_x=[0.5 0.2];
%     sigma_x=[0.5 0.2; 0.2 0.5];
    xi_x_all=mvnrnd(mu_x,sigma_x,n);
    
    xi_y_all=xi_yt(:,:,i);%cov(xi_y) has same sturcture as z,
    %but xi_b1 and xi_s1 have AR(1)correlation respectively.
    
    %Bivariate setting(4 dimesion) for Z.
    mu_z=zeros(1,4);
    sigma_z1=[0.5 0; 0 0.2];sigma_z2=[0.2 0.15;0.15 0.1]; %setting in xy02z02
    sigma_z=[sigma_z1 sigma_z2;sigma_z2' sigma_z1];
    %     sigma_z=diag([0.5,0.2,0.1,0.5,0.2,0.1]);
    xi_z_all=mvnrnd(mu_z,sigma_z,m*n);
    
    xi_b{1}=xi_x_all(:,1);
    xi_b{2}=xi_x_all(:,2);
    xi_b{3}=xi_y_all(:,1);
    xi_b{4}=xi_y_all(:,2);
    xi_b{5}=xi_z_all(:,1);
    xi_b{6}=xi_z_all(:,2);
    
    
    xi_s{1}=xi_x_all(:,3);
    xi_s{2}=xi_x_all(:,4);
    xi_s{3}=xi_y_all(:,3);
    xi_s{4}=xi_y_all(:,4);
    xi_s{5}=xi_z_all(:,3);
    xi_s{6}=xi_z_all(:,4);
    
    [data_b]=sim_bs_fun(m,n,xi_b);
    DATA_B{i}=data_b;
    XI_B{i}=xi_b;
    [data_s]=sim_bs_fun(m,n,xi_s);
    DATA_S{i}=data_s;
    XI_S{i}=xi_s;
    
end

save -v7.3 data50_mn200_bs DATA_B XI_B DATA_S XI_S
